backend:
  name: github
  repo: utzen2014/UtkuZENGIN
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Yazıları"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Tarih", name: "date", widget: "datetime" }
      - { label: "Özet / Açıklama", name: "description", widget: "text" }
      - { label: "İçerik", name: "body", widget: "markdown" }
